=== HubUser99/XML-VAMK/Assignment3/task_3.xsd
<?xml version="1.0"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://myNamespace.com"
	xmlns:mstns="http://myNamespace.com"
	targetNamespace="http://myNamespace.com"
	elementFormDefault="qualified"
>
	<xs:element name="task_3">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="flights" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="flight" maxOccurs="unbounded" type="flightType"/>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="uniqueFlightNumbers">
						<xs:selector xpath="mstns:flight"/>
						<xs:field xpath="@flightNumber"/>
					</xs:unique>
				</xs:element>
				<xs:element name="passengers" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="passenger" maxOccurs="unbounded" type="passengerType"/>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="uniqueSeatNumbers">
						<xs:selector xpath="mstns:passenger"/>
						<xs:field xpath="@seatNumber"/>
					</xs:unique>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="flightType" mixed="true">
		<xs:sequence>
			<xs:element name="dateAndTime" type="xs:date"/>
			<xs:element name="origin" type="xs:string"/>
			<xs:element name="destination" type="xs:string"/>
			<xs:element name="price">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
		        		<xs:fractionDigits value="2" />
		    		</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
		<xs:attribute  name="flightNumber">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[A-Z][5-9]{4}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="passengerType" mixed="true">
		<xs:sequence>
			<xs:element name="flightNumber">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[A-Z][5-9]{4}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="firstName" type="xs:string"/>
			<xs:element name="lastName" type="xs:string"/>
			<xs:element name="phoneNumber">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[+][0-9]{3}[-][0-9]{2}[-][0-9]{7}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="diet">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="vegetarian"/>
						<xs:enumeration value="carnivore"/>
						<xs:enumeration value="allergic"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="travellingClass">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="business"/>
						<xs:enumeration value="plus"/>
						<xs:enumeration value="economy"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
		<xs:attribute  name="seatNumber">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[_][1-9][0-5]"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== HubUser99/XML-VAMK/Assignment3/task_3.xml
<?xml version="1.0" standalone="yes"?>

<task_3
	xmlns="http://myNamespace.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://myNamespace.com task_3.xsd"
>
	<flights>
		<flight flightNumber="A5678">
			<dateAndTime>2019-10-25</dateAndTime>
			<origin>Vaasa</origin>
			<destination>Helsinki</destination>
			<price>299.50</price>
		</flight>
		<flight flightNumber="B6789">
			<dateAndTime>2019-11-27</dateAndTime>
			<origin>Helsinki</origin>
			<destination>Tampere</destination>
			<price>329.65</price>
		</flight>
		<flight flightNumber="C7856">
			<dateAndTime>2019-12-05</dateAndTime>
			<origin>Tampere</origin>
			<destination>Rovaniemi</destination>
			<price>555.15</price>
		</flight>
	</flights>
	<passengers>
		<passenger seatNumber="_10">
			<flightNumber>A5678</flightNumber>
			<firstName>Joe</firstName>
			<lastName>Doe</lastName>
			<phoneNumber>+358-40-1234567</phoneNumber>
			<diet>vegetarian</diet>
			<travellingClass>business</travellingClass>
		</passenger>
		<passenger seatNumber="_21">
			<flightNumber>B6789</flightNumber>
			<firstName>John</firstName>
			<lastName>Don</lastName>
			<phoneNumber>+358-40-1234567</phoneNumber>
			<diet>carnivore</diet>
			<travellingClass>plus</travellingClass>
		</passenger>
		<passenger seatNumber="_32">
			<flightNumber>B6789</flightNumber>
			<firstName>Joseph</firstName>
			<lastName>Don</lastName>
			<phoneNumber>+358-40-1234567</phoneNumber>
			<diet>allergic</diet>
			<travellingClass>economy</travellingClass>
		</passenger>
		<passenger seatNumber="_43">
			<flightNumber>A5678</flightNumber>
			<firstName>Jane</firstName>
			<lastName>Doe</lastName>
			<phoneNumber>+358-40-1234567</phoneNumber>
			<diet>vegetarian</diet>
			<travellingClass>business</travellingClass>
		</passenger>
		<passenger seatNumber="_54">
			<flightNumber>C7856</flightNumber>
			<firstName>Jenifer</firstName>
			<lastName>Dane</lastName>
			<phoneNumber>+358-40-1234567</phoneNumber>
			<diet>carnivore</diet>
			<travellingClass>plus</travellingClass>
		</passenger>
	</passengers>
</task_3>
